# Preload data and group into batches

In [1]:
import tensorflow as tf
import numpy as np

X = np.random.random([100, 4])
y_ = np.random.random([100, 1])

features, label = tf.train.slice_input_producer([X, y_], num_epochs=2, shuffle=True)
features_batch, label_batch = tf.train.batch([features, label], batch_size=3)

s = tf.Session()
s.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=s, coord=coord)
print 'threads', len(threads)

a, b = s.run([features_batch, label_batch])
print a.shape, b.shape
print a
print b

n = 0
try:
    while not coord.should_stop():
        batchx, batchy = s.run([features_batch, label_batch])
        print batchx.shape
        n += batchx.shape[0]
except tf.errors.OutOfRangeError:
    pass
finally:
    coord.request_stop()
    coord.join(threads)

print 'n', n


threads 4
(3, 4) (3, 1)
[[ 0.08450093  0.39438438  0.33074995  0.24575709]
 [ 0.73295833  0.24270713  0.24469169  0.8833358 ]
 [ 0.03074347  0.944733    0.42114829  0.60533895]]
[[ 0.68470433]
 [ 0.57721224]
 [ 0.70196197]]
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
(3, 4)
n 195
