In [25]:
import tensorflow as tf
import numpy as np

A = np.zeros([9, 9])
for i in range(9):
    for j in range(9):
        A[i][j] = (i+1) * (j+1)
        
print 'A=', A

B = tf.slice(A, [0, 3], [-1, 2])
print B

sess = tf.InteractiveSession()

print 'B=', B.eval()

 A= [[  1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.]]
Tensor("Slice_20:0", shape=(9, 2), dtype=float64)
B= [[  4.   5.]
 [  8.  10.]
 [ 12.  15.]
 [ 16.  20.]
 [ 20.  25.]
 [ 24.  30.]
 [ 28.  35.]
 [ 32.  40.]
 [ 36.  45.]]


In [21]:
x = tf.nn.softmax(np.random.normal(0, 1, 4))
y = tf.nn.softmax(np.random.normal(0, 1, 4))

z = tf.reshape(tf.stack([x, y]), [-1, 8])

a, b, c = sess.run([x, y, z])
print a
print b
print c

[ 0.27143122  0.48745281  0.20146523  0.03965075]
[ 0.10249797  0.57607684  0.27447719  0.04694799]
[[ 0.27143122  0.48745281  0.20146523  0.03965075  0.10249797  0.57607684
   0.27447719  0.04694799]]
