In [1]:
import numpy as np
import tensorflow as tf

tf.enable_eager_execution()

/usr/local/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# hash

不推荐用string_to_hash_bucket，而推荐显式用这两个

- string_to_hash_bucket_fast：可信环境，并且速度快
- string_to_hash_bucket_strong：需要安全的情况

In [10]:
print(tf.string_to_hash_bucket("a", num_buckets=100))
print(tf.string_to_hash_bucket_fast("a", num_buckets=100))
print(tf.string_to_hash_bucket_strong("a", num_buckets=100, key=[1, 1]))

tf.Tensor(68, shape=(), dtype=int64)
tf.Tensor(39, shape=(), dtype=int64)
tf.Tensor(70, shape=(), dtype=int64)


# Joining

string_join处理一维的string list
reduce_join处理多维的string tensor，沿着axis reduce join

In [13]:
print(tf.string_join(["a", "b"], ","))
print(tf.reduce_join([["a", "b"], ["c", "d"]], axis=1))

tf.Tensor(b'a,b', shape=(), dtype=string)
tf.Tensor([b'ab' b'cd'], shape=(2,), dtype=string)


# Spliting

In [20]:
res = tf.string_split(["abc", "123"], "")
print(res)
tf.sparse_tensor_to_dense(res)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]], shape=(6, 2), dtype=int64), values=tf.Tensor([b'a' b'b' b'c' b'1' b'2' b'3'], shape=(6,), dtype=string), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))


SystemError: <built-in function TFE_Py_FastPathExecute> returned NULL without setting an error

In [22]:
tf.substr("1234", pos=1, len=2)

<tf.Tensor: id=110, shape=(), dtype=string, numpy=b'23'>

# Conversion

In [25]:
tf.as_string([1, 2, 3])

<tf.Tensor: id=117, shape=(3,), dtype=string, numpy=array([b'1', b'2', b'3'], dtype=object)>

In [27]:
tf.string_to_number("123")

<tf.Tensor: id=123, shape=(), dtype=float32, numpy=123.0>

In [41]:
tf.decode_raw("abc", tf.uint8)

<tf.Tensor: id=148, shape=(3,), dtype=uint8, numpy=array([97, 98, 99], dtype=uint8)>

In [49]:
import struct
b = struct.pack("4f", 1, 2, 3, 4)
print(len(b))
print(repr(b))
print(tf.decode_raw(b, tf.float32))
print(tf.decode_raw(b, tf.float64))

16
b'\x00\x00\x80?\x00\x00\x00@\x00\x00@@\x00\x00\x80@'
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([  2.00000047 512.00012255], shape=(2,), dtype=float64)


In [61]:
tf.decode_csv('a,,c', record_defaults=["1", "2", "3"])

[<tf.Tensor: id=229, shape=(), dtype=string, numpy=b'a'>,
 <tf.Tensor: id=230, shape=(), dtype=string, numpy=b'2'>,
 <tf.Tensor: id=231, shape=(), dtype=string, numpy=b'c'>]

In [68]:
import base64

print(tf.encode_base64("abc"))
print(base64.b64encode(b"abc"))

tf.Tensor(b'YWJj', shape=(), dtype=string)
b'YWJj'


In [69]:
print(tf.decode_base64(tf.encode_base64("abc")))

tf.Tensor(b'abc', shape=(), dtype=string)
